#!/bin/sh

# ============================================
# NWHR BSPWM Config
# ============================================

# -- Autostart -- #
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
picom --config $HOME/.config/picom/picom.conf &
feh --bg-fill $HOME/wallpapers/wallpaper.jpg &

# -- Auto resolution -- #
xrandr_output=$(xrandr | grep ' connected' | head -n 1 | awk '{print $1}')
xrandr_res=$(xrandr | grep ' connected' -A1 | tail -n 1 | awk '{print $1}')
xrandr --output "$xrandr_output" --mode "$xrandr_res" --rate 60

# -- Workspaces -- #
bspc monitor -d I II III IV V VI VII VIII IX X

# -- Window Config -- #
bspc config border_width            2
bspc config window_gap              10
bspc config top_padding             35
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

# -- Colors -- #
bspc config normal_border_color     "#2e2e2e"
bspc config active_border_color     "#2e2e2e"
bspc config focused_border_color    "#c8c8c8"
bspc config presel_feedback_color   "#555555"

# -- Rules -- #
bspc rule -a Firefox desktop='^2'
bspc rule -a Alacritty state=tiled

# -- Cursor -- #
xsetroot -cursor_name left_ptr
